'use client'

import { useState, type FormEvent } from 'react'
import { isCtaSection, type SiteDefinition } from '@bakerrang/site-schema'
import { Input, Textarea } from '@bakerrang/ui'
import { ApiError } from '../../lib/api'
import { updateSectionContent, type LinkActionInput } from '../../lib/site'
import { SectionActionFields, type SectionActionType } from './SectionActionFields'
import { WebsiteEditorShell } from './WebsiteEditorShell'

export function CtaEditor ({ pageId, sectionId, tenantId, site, onCancel, onDirtyChange = () => {}, onSaved }: { pageId: string, sectionId: string, tenantId: string, site: SiteDefinition, onCancel: () => void, onDirtyChange?: (dirty: boolean) => void, onSaved: (site: SiteDefinition) => void }) {
  const section = site.pages.find((page) => page.id === pageId)?.sections.find((item) => item.id === sectionId); const cta = section && isCtaSection(section) ? section : undefined
  const [heading, setHeading] = useState(cta?.content.heading ?? 'Ready to get started?'); const [body, setBody] = useState(cta?.content.body ?? ''); const [buttonLabel, setButtonLabel] = useState(cta?.content.buttonLabel ?? ''); const [actionType, setActionType] = useState<SectionActionType>(cta?.content.action?.type ?? 'url'); const [actionValue, setActionValue] = useState(cta?.content.action?.value ?? ''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!heading.trim()) return setError('Heading is required.'); if (Boolean(buttonLabel.trim()) !== Boolean(actionValue.trim())) return setError('Button label and action must be provided together.'); setSaving(true); setError(null); try { onSaved(await updateSectionContent(tenantId, pageId, sectionId, { heading: heading.trim(), ...(body.trim() ? { body: body.trim() } : {}), ...(buttonLabel.trim() ? { buttonLabel: buttonLabel.trim(), action: { type: actionType, value: actionValue.trim() } as LinkActionInput } : {}) })) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save Call to Action.') } finally { setSaving(false) } }
  return <WebsiteEditorShell dirtyValue={{ heading, body, buttonLabel, actionType, actionValue }} editor="cta" error={error} onCancel={onCancel} onDirtyChange={onDirtyChange} onSubmit={(event) => void submit(event)} saving={saving}><label className="text-sm font-semibold text-fg" htmlFor={`cta-heading-${tenantId}`}>Heading</label><Input className="mt-2" id={`cta-heading-${tenantId}`} maxLength={120} onChange={(event) => setHeading(event.target.value)} value={heading} /><label className="mt-4 block text-sm font-semibold text-fg" htmlFor={`cta-body-${tenantId}`}>Body <span className="font-normal text-fg-muted">Optional</span></label><Textarea className="mt-2" id={`cta-body-${tenantId}`} maxLength={300} onChange={(event) => setBody(event.target.value)} value={body} /><label className="mt-4 block text-sm font-semibold text-fg" htmlFor={`cta-button-${tenantId}`}>Button Label <span className="font-normal text-fg-muted">Optional — add both fields to show a button</span></label><Input className="mt-2" id={`cta-button-${tenantId}`} maxLength={60} onChange={(event) => setButtonLabel(event.target.value)} value={buttonLabel} /><SectionActionFields disabled={saving} id={`cta-${tenantId}`} onTypeChange={setActionType} onValueChange={setActionValue} type={actionType} value={actionValue} /></WebsiteEditorShell>
}
