/* eslint-disable @next/next/no-img-element */
'use client'

import { useEffect, useRef, useState, type FormEvent } from 'react'
import { findHomePage, isLogosSection, type SiteDefinition } from '@bakerrang/site-schema'
import { Button, FileInput, Input } from '@bakerrang/ui'
import { ApiError } from '../../lib/api'
import { getMedia, uploadMedia, type MediaItem } from '../../lib/media'
import { upsertHomeLogos } from '../../lib/site'
import { RowActions } from './RowActions'
import { WebsiteEditorShell } from './WebsiteEditorShell'

type Row = { key: string, id?: string, mediaId: string, altText: string, src?: string, width?: number, height?: number }
export function LogosEditor ({ sectionId, tenantId, site, onCancel, onDirtyChange = () => {}, onSaved }: { sectionId: string, tenantId: string, site: SiteDefinition, onCancel: () => void, onDirtyChange?: (dirty: boolean) => void, onSaved: (site: SiteDefinition) => void }) {
  const section = findHomePage(site)?.sections.find((item) => item.id === sectionId); const logos = section && isLogosSection(section) ? section : undefined
  const [heading, setHeading] = useState(logos?.content.heading ?? 'Trusted by'); const [rows, setRows] = useState<Row[]>(() => logos?.content.items.map((item) => ({ key: item.id, ...item })) ?? []); const [media, setMedia] = useState<MediaItem[]>([]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const uploadInput = useRef<HTMLInputElement>(null)
  useEffect(() => { void getMedia(tenantId).then((result) => setMedia(result.media)).catch(() => setError('Unable to load images.')) }, [tenantId])
  const move = (index: number, delta: number) => setRows((items) => { const target = index + delta; if (target < 0 || target >= items.length) return items; const copy = [...items]; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy })
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (rows.some((row) => !row.altText.trim())) return setError('Every logo needs alt text.'); setSaving(true); setError(null); try { onSaved(await upsertHomeLogos(tenantId, sectionId, { ...(heading.trim() ? { heading: heading.trim() } : {}), items: rows.map(({ id, mediaId, altText }) => ({ ...(id ? { id } : {}), mediaId, altText: altText.trim() })) })) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save Logos.') } finally { setSaving(false) } }
  const upload = async (file: File | undefined) => { if (!file) return; try { const item = await uploadMedia(tenantId, file); setMedia((items) => [item, ...items]); if (uploadInput.current) uploadInput.current.value = '' } catch { setError('Unable to upload the logo image.') } }
  return <WebsiteEditorShell dirtyValue={{ heading, rows: rows.map(({ id, mediaId, altText }) => ({ id, mediaId, altText })) }} editor="logos" error={error} onCancel={onCancel} onDirtyChange={onDirtyChange} onSubmit={(event) => void submit(event)} saving={saving} width="wide"><label className="text-sm font-semibold text-fg" htmlFor={`logos-heading-${tenantId}`}>Heading <span className="font-normal text-fg-muted">Optional</span></label><Input className="mt-2" id={`logos-heading-${tenantId}`} maxLength={120} onChange={(event) => setHeading(event.target.value)} value={heading} /><section className="mt-5"><h3 className="text-sm font-semibold text-fg">Media Library</h3><FileInput accept="image/jpeg,image/png,image/webp" className="mt-3" id={`logos-upload-${tenantId}`} onChange={(event) => void upload(event.target.files?.[0])} ref={uploadInput} /><div className="mt-3 grid gap-3 sm:grid-cols-3">{media.map((item) => <div className="rounded border border-border p-2" key={item.id}><img alt="" className="aspect-video w-full object-cover" height={item.height} src={item.src} width={item.width} /><Button className="mt-2 w-full" disabled={rows.some((row) => row.mediaId === item.id) || rows.length >= 24} onClick={() => setRows((items) => [...items, { key: `new-${item.id}`, mediaId: item.id, altText: '', src: item.src, width: item.width, height: item.height }])} size="sm" type="button">Add logo</Button></div>)}</div></section><ol className="mt-5 space-y-3">{rows.map((row, index) => <li className="rounded border border-border p-3" key={row.key}><label className="text-sm font-semibold text-fg" htmlFor={`logo-alt-${tenantId}-${row.key}`}>Logo {index + 1} alt text</label><Input className="mt-2" id={`logo-alt-${tenantId}-${row.key}`} maxLength={250} onChange={(event) => setRows((items) => items.map((item) => item.key === row.key ? { ...item, altText: event.target.value } : item))} value={row.altText} /><RowActions className="mt-2" moveDown={{ label: 'Move logo down', disabled: index === rows.length - 1, onClick: () => move(index, 1) }} moveUp={{ label: 'Move logo up', disabled: index === 0, onClick: () => move(index, -1) }} remove={{ label: 'Remove logo', onClick: () => setRows((items) => items.filter((item) => item.key !== row.key)) }} /></li>)}</ol></WebsiteEditorShell>
}
