'use client'

import { useRef, useState, type FormEvent } from 'react'
import { isStatsSection, type SiteDefinition } from '@bakerrang/site-schema'
import { Button, Input, Textarea } from '@bakerrang/ui'
import { ApiError } from '../../lib/api'
import { updateSectionContent } from '../../lib/site'
import { RowActions } from './RowActions'
import { WebsiteEditorShell } from './WebsiteEditorShell'

type Row = { key: string, id?: string, value: string, label: string }
export function StatsEditor ({ pageId, sectionId, tenantId, site, onCancel, onDirtyChange = () => {}, onSaved }: { pageId: string, sectionId: string, tenantId: string, site: SiteDefinition, onCancel: () => void, onDirtyChange?: (dirty: boolean) => void, onSaved: (site: SiteDefinition) => void }) {
  const section = site.pages.find((page) => page.id === pageId)?.sections.find((item) => item.id === sectionId); const stats = section && isStatsSection(section) ? section : undefined
  const next = useRef(1); const [heading, setHeading] = useState(stats?.content.heading ?? ''); const [intro, setIntro] = useState(stats?.content.intro ?? '')
  const [rows, setRows] = useState<Row[]>(() => stats?.content.items.map((item) => ({ key: item.id, id: item.id, value: item.value, label: item.label })) ?? [{ key: 'new-0', value: '', label: '' }]); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const move = (index: number, delta: number) => setRows((items) => { const target = index + delta; if (target < 0 || target >= items.length) return items; const copy = [...items]; [copy[index], copy[target]] = [copy[target], copy[index]]; return copy })
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!rows.length || rows.some((row) => !row.value.trim() || !row.label.trim())) return setError('Every highlight needs a value and label.'); setSaving(true); setError(null); try { onSaved(await updateSectionContent(tenantId, pageId, sectionId, { ...(heading.trim() ? { heading: heading.trim() } : {}), ...(intro.trim() ? { intro: intro.trim() } : {}), items: rows.map(({ id, value, label }) => ({ ...(id ? { id } : {}), value: value.trim(), label: label.trim() })) })) } catch (caught) { setError(caught instanceof ApiError ? caught.message : 'Unable to save Highlights.') } finally { setSaving(false) } }
  return <WebsiteEditorShell dirtyValue={{ heading, intro, rows }} editor="stats" error={error} onCancel={onCancel} onDirtyChange={onDirtyChange} onSubmit={(event) => void submit(event)} saving={saving} width="wide"><label className="text-sm font-semibold text-fg" htmlFor={`stats-heading-${tenantId}`}>Heading <span className="font-normal text-fg-muted">Optional</span></label><Input className="mt-2" id={`stats-heading-${tenantId}`} maxLength={120} onChange={(event) => setHeading(event.target.value)} value={heading} /><label className="mt-4 block text-sm font-semibold text-fg" htmlFor={`stats-intro-${tenantId}`}>Intro <span className="font-normal text-fg-muted">Optional</span></label><Textarea className="mt-2" id={`stats-intro-${tenantId}`} maxLength={300} onChange={(event) => setIntro(event.target.value)} value={intro} /><div className="mt-5 space-y-3">{rows.map((row, index) => <fieldset className="rounded-md border border-border p-4" key={row.key}><legend className="px-1 text-sm font-semibold text-fg">Highlight {index + 1}</legend><Input aria-label={`Highlight ${index + 1} value`} maxLength={16} onChange={(event) => setRows((items) => items.map((item) => item.key === row.key ? { ...item, value: event.target.value } : item))} value={row.value} /><Input aria-label={`Highlight ${index + 1} label`} className="mt-3" maxLength={60} onChange={(event) => setRows((items) => items.map((item) => item.key === row.key ? { ...item, label: event.target.value } : item))} value={row.label} /><RowActions className="mt-2" moveDown={{ label: 'Move highlight down', disabled: index === rows.length - 1, onClick: () => move(index, 1) }} moveUp={{ label: 'Move highlight up', disabled: index === 0, onClick: () => move(index, -1) }} remove={{ label: 'Delete highlight', onClick: () => setRows((items) => items.filter((item) => item.key !== row.key)) }} /></fieldset>)}</div><Button className="mt-4" disabled={rows.length >= 8} onClick={() => setRows((items) => [...items, { key: `new-${next.current++}`, value: '', label: '' }])} size="sm" type="button" variant="secondary">Add highlight</Button></WebsiteEditorShell>
}
